version: "3.7"

services:
  #  client:
  #    build:
  #      context: ./client
  #      dockerfile: Dockerfile
  #    container_name: client
  #    depends_on:
  #      - api
  #    restart: always
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - ./client:/client
  #      - notused:/opt/app/node_modules
  #    networks:
  #      - dockerNetwork

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    restart: always
    container_name: api_server
    depends_on:
      - mongodb
    ports:
      - 3000:3000
      - 56745:56745
    links:
      - mongodb
    volumes:
      - ./api:/opt/app
      - notused:/opt/app/node_modules
    networks:
      - dockerNetwork

  mongodb:
    #    image: mongo:4.0.10
    build:
      context: ./mongo
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    restart: always
    container_name: mongodb
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/mongo.conf:/etc/mongod.conf
    ports:
      - 27017:27017
#    command: mongod --config /etc/mongo.conf --smallfiles --bind_ip_all && mongod use biblos && mongod
    networks:
      - dockerNetwork

volumes:
  notused:
  data-node:

networks:
  dockerNetwork:
    driver: bridge